{
	["source"] = "import",
	["auto"] = true,
	["url"] = "twitch.tv/MeeresTV",
	["displayIcon"] = 3528301,
	["id"] = "Infernal Fusion",
	["regionType"] = "icon",
	["height"] = 55,
	["parent"] = "1. Icons - High Priority",
	["anchorPoint"] = "CENTER",
	["config"] = {
	},
	["cooldownSwipe"] = true,
	["color"] = {
		1,
		1,
		1,
		1,
	},
	["iconSource"] = -1,
	["alpha"] = 1,
	["cooldownEdge"] = false,
	["stickyDuration"] = false,
	["selfPoint"] = "CENTER",
	["conditions"] = {
	},
	["customTextUpdate"] = "update",
	["width"] = 55,
	["uid"] = "R1Jz0bGZP2M",
	["actions"] = {
		["init"] = {
		},
		["start"] = {
			["do_sound"] = false,
			["sound"] = "Interface\\AddOns\\WeakAuras\\Media\\Sounds\\Torch.ogg",
		},
		["finish"] = {
		},
	},
	["subRegions"] = {
		{
			["type"] = "subbackground",
		},
		{
			["text_font"] = "Friz Quadrata TT",
			["anchorXOffset"] = 0,
			["anchorYOffset"] = 0,
			["text_selfPoint"] = "AUTO",
			["text_wordWrap"] = "WordWrap",
			["text_anchorYOffset"] = 0,
			["rotateText"] = "NONE",
			["text_fontType"] = "OUTLINE",
			["text_automaticWidth"] = "Auto",
			["text_shadowXOffset"] = 0,
			["text_text_format_tooltip1_format"] = "none",
			["text_justify"] = "CENTER",
			["text_fontSize"] = 14,
			["text_text"] = "Big Dot",
			["text_color"] = {
				0.98823529411765,
				0.99607843137255,
				1,
				1,
			},
			["text_visible"] = true,
			["text_fixedWidth"] = 64,
			["text_shadowColor"] = {
				0,
				0,
				0,
				1,
			},
			["type"] = "subtext",
			["text_anchorXOffset"] = 0,
			["text_shadowYOffset"] = 0,
			["text_anchorPoint"] = "OUTER_BOTTOM",
			["text_text_format_s_format"] = "none",
		},
		{
			["text_font"] = "Friz Quadrata TT",
			["anchorXOffset"] = 0,
			["anchorYOffset"] = 0,
			["text_selfPoint"] = "AUTO",
			["text_wordWrap"] = "WordWrap",
			["text_anchorYOffset"] = -6,
			["rotateText"] = "NONE",
			["text_text_format_1.ttoltip1_format"] = "none",
			["text_anchorXOffset"] = 7,
			["text_fontType"] = "OUTLINE",
			["text_automaticWidth"] = "Auto",
			["text_fontSize"] = 20,
			["text_shadowXOffset"] = 0,
			["text_text_format_tooltip2_format"] = "none",
			["text_justify"] = "CENTER",
			["text_visible"] = true,
			["text_text"] = "%s",
			["text_color"] = {
				0.98823529411765,
				0.99607843137255,
				1,
				1,
			},
			["type"] = "subtext",
			["text_fixedWidth"] = 64,
			["text_shadowColor"] = {
				0,
				0,
				0,
				1,
			},
			["text_text_format_1.tooltip1_format"] = "none",
			["text_shadowYOffset"] = 0,
			["text_text_format_tooltip1_format"] = "none",
			["text_anchorPoint"] = "INNER_BOTTOMRIGHT",
			["text_text_format_s_format"] = "none",
		},
		{
			["glowThickness"] = 1,
			["glow"] = false,
			["glowBorder"] = false,
			["glowXOffset"] = 0,
			["type"] = "subglow",
			["glowFrequency"] = 0.25,
			["glowLines"] = 8,
			["useGlowColor"] = false,
			["glowScale"] = 1,
			["glowColor"] = {
				1,
				1,
				1,
				1,
			},
			["glowYOffset"] = 0,
			["glowLength"] = 10,
			["glowType"] = "Pixel",
		},
	},
	["cooldown"] = true,
	["semver"] = "1.0.4",
	["version"] = 5,
	["xOffset"] = 0,
	["yOffset"] = 0,
	["inverse"] = false,
	["zoom"] = 0,
	["animation"] = {
		["finish"] = {
			["easeType"] = "none",
			["duration_type"] = "seconds",
			["type"] = "none",
			["easeStrength"] = 3,
		},
		["start"] = {
			["easeType"] = "none",
			["duration_type"] = "seconds",
			["type"] = "none",
			["easeStrength"] = 3,
		},
		["main"] = {
			["easeType"] = "none",
			["duration_type"] = "seconds",
			["type"] = "none",
			["easeStrength"] = 3,
		},
	},
	["cooldownTextDisabled"] = false,
	["desaturate"] = false,
	["authorOptions"] = {
	},
	["internalVersion"] = 65,
	["tocversion"] = 100100,
	["anchorFrameType"] = "SCREEN",
	["icon"] = true,
	["information"] = {
		["forceEvents"] = true,
		["ignoreOptionsEventErrors"] = true,
	},
	["keepAspectRatio"] = false,
	["load"] = {
		["race"] = {
			["multi"] = {
			},
		},
		["talent"] = {
			["multi"] = {
			},
		},
		["size"] = {
			["multi"] = {
			},
		},
		["talent2"] = {
			["multi"] = {
			},
		},
		["class"] = {
			["multi"] = {
			},
		},
		["use_encounterid"] = true,
		["spec"] = {
			["multi"] = {
			},
		},
		["zoneIds"] = "",
		["faction"] = {
			["multi"] = {
			},
		},
		["role"] = {
			["multi"] = {
				["TANK"] = true,
			},
			["single"] = "TANK",
		},
		["use_zoneIds"] = false,
		["difficulty"] = {
			["multi"] = {
			},
		},
		["encounterid"] = "2688",
		["ingroup"] = {
			["multi"] = {
			},
		},
		["pvptalent"] = {
			["multi"] = {
			},
		},
	},
	["frameStrata"] = 1,
	["useCooldownModRate"] = true,
	["triggers"] = {
		{
			["trigger"] = {
				["use_track"] = true,
				["use_genericShowOn"] = true,
				["name_operator"] = "find('%s')",
				["check"] = "event",
				["fetchTooltip"] = true,
				["unevent"] = "auto",
				["use_debuffClass"] = false,
				["genericShowOn"] = "showOnCooldown",
				["spellName"] = 0,
				["debuffType"] = "HARMFUL",
				["type"] = "aura2",
				["unit"] = "player",
				["realSpellName"] = 0,
				["use_absorbHealMode"] = true,
				["useName"] = true,
				["spellIds"] = {
					283573,
				},
				["use_spellId"] = true,
				["useRem"] = false,
				["custom_hide"] = "timed",
				["customVariables"] = "{\n    expirationTime = true,\n    spellID = \"number\",\n}\n\n\n",
				["subeventSuffix"] = "_CAST_START",
				["fetchRaidMark"] = false,
				["name"] = "Plasma Discharge",
				["remOperator"] = "<",
				["auraspellids"] = {
				},
				["use_spellName"] = true,
				["events"] = "CHAT_MSG_RAID_BOSS_EMOTE",
				["rem"] = "3",
				["use_unit"] = true,
				["subeventPrefix"] = "SPELL",
				["duration"] = "3",
				["names"] = {
					"Sacred Blade",
				},
				["auranames"] = {
					"Infernal Fusion",
					"408147",
				},
				["buffShowOn"] = "showOnActive",
				["useGroup_count"] = false,
				["matchesShowOn"] = "showOnActive",
				["ignoreSelf"] = true,
				["use_absorbMode"] = true,
				["event"] = "Cast",
				["group_countOperator"] = ">",
				["combineMatches"] = "showLowest",
				["useExactSpellId"] = false,
				["use_tooltip"] = false,
				["custom_type"] = "event",
				["showClones"] = false,
				["spellId"] = 361644,
				["group_count"] = "0",
			},
			["untrigger"] = {
			},
		},
		["activeTriggerMode"] = -10,
		["disjunctive"] = "all",
	},
}