authorOptions = {
    {
        ["key"] = "autoRefresh",
        ["name"] = "autoRefresh",
        ["type"] = "toggle",
        ["default"] = false,
    },
    {
        ["key"] = "minimumRioScoreEnabled",
        ["name"] = "minimumRioScoreEnabled",
        ["type"] = "toggle",
        ["default"] = false,
    },
    {
        ["key"] = "minimumRioScoreInput",
        ["name"] = "minimumRioScoreInput",
        ["type"] = "number",
        ["min"] = 0,
        ["max"] = 9999,
        ["step"] = 1,
        ["default"] = 2500,
    },
    {
        ["key"] = "AA",
        ["name"] = "AA",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "AV",
        ["name"] = "AV",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "COS",
        ["name"] = "COS",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "HOV",
        ["name"] = "HOV",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "NO",
        ["name"] = "NO",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "RLP",
        ["name"] = "RLP",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "SBG",
        ["name"] = "SBG",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "TJS",
        ["name"] = "TJS",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "givesScoreAtKeyLevelEnabled",
        ["name"] = "givesScoreAtKeyLevelEnabled",
        ["type"] = "toggle",
        ["default"] = false,
    },
    {
        ["key"] = "givesScoreAtKeyLevelInput",
        ["name"] = "givesScoreAtKeyLevelInput",
        ["type"] = "number",
        ["min"] = 0,
        ["max"] = 99,
        ["step"] = 1,
        ["default"] = 0,
    },
    {
        ["key"] = "hasSlotForPlayerClass",
        ["name"] = "hasSlotForPlayerClass",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "hasSlotForPlayerRole",
        ["name"] = "hasSlotForPlayerRole",
        ["type"] = "toggle",
        ["default"] = true,
    },
    {
        ["key"] = "hasSlotsForPartyRoles",
        ["name"] = "hasSlotsForPartyRoles",
        ["type"] = "toggle",
        ["default"] = false,
    },
    {
        ["key"] = "hasBloodlust",
        ["name"] = "hasBloodlust",
        ["type"] = "toggle",
        ["default"] = false,
    },
    {
        ["key"] = "hasCurseDispel",
        ["name"] = "hasCurseDispel",
        ["type"] = "toggle",
        ["default"] = false,
    },
    {
        ["key"] = "hasPoisonDispel",
        ["name"] = "hasPoisonDispel",
        ["type"] = "toggle",
        ["default"] = false,
    },
}
